name: Code checks

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

env:
  python-version: "3.8"
  PYTHONIOENCODING: UTF-8

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
            venv-path: source venv/bin/activate
          - os: macos-latest
            path: ~/Library/Caches/pip
            venv-path: source venv/bin/activate
          - os: windows-latest
            path: ~\AppData\Local\pip\Cache
            venv-path: venv\Scripts\activate.bat
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}

      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: requirements.txt

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - run: pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Run FirstStep test
        run: python -m unittest tests_stand.TestTestCase
