name: Code checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PYTHONIOENCODING: UTF-8

jobs:
  create-virtualenv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - run: pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

  build:
    needs: create-virtualenv

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
            venv-path: source venv/bin/activate
          - os: macos-latest
            path: ~/Library/Caches/pip
            venv-path: source venv/bin/activate
          - os: windows-latest
            path: ~\AppData\Local\pip\Cache
            venv-path: venv\Scripts\activate.bat
        python-version: [3.9]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - name: Run FirstStep test
        run: python -m unittest tests_stand.TestTestCase
